graph TD
    A[Home] --> B[Campgrounds]
    A --> C[About Us]
    A --> D[Contact Us]
    A --> E[Login]
    A --> F[Register]
    B --> G[Campground Details]
    B --> H[New Campground-Admin]
    B --> I[Edit Campground-Admin]
    B --> J[Search Results]
    G --> K[Book Campground]
    G --> L[Leave Review]
    G --> M[Delete Review]
    A --> N[Admin Dashboard]
    N --> O[Manage Users]
    N --> P[Manage Bookings]
    N --> Q[View Transactions]
    N --> R[Manage Campgrounds]